# Template config, need to change dump_dir, data.root_dir and data.tokenizer.path

# dump_dir: !!CHANGETHIS!!

dump_dir: /fsx-storygen/jwzhao/yangzho6/lingua/checkpoints/debug 

name: "debug"
steps: 1000
probe_freq: 100
seed: 777
optim:
    lr: 3.0e-5 
    warmup: 2000 
    lr_min_ratio: 0.000003 
    clip: 10.0

distributed:
    fsdp_type: full_shard
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    tp_size: 1

model:
    dim: 8192 
    n_layers: 8
    n_heads: 8

data:
    root_dir: data/shuffled
    sources:
        megamath_pro_web: 1.0 
    batch_size: 2 
    prefetch_size: 64
    seq_len: 8192 
    n_views: 2
    load_async: true
    tokenizer:
        name: bytes 
        path: /fsx-storygen/jwzhao/yangzho6/lingua/setup/tokenizerllama 

profiling:
    run: true

checkpoint:
    init_ckpt_path: /fsx-storygen/jwzhao/yangzho6/lingua/checkpoints/debug/checkpoints/Llama-3.2-3Bdcp 
    dump:
        every: 100
        keep: 1
    eval:
        every: 100
        keep: 1

logging:
    freq: 10

eval:
    generator:
        max_tokens: 8192
        dtype: bf16
        temperature: 1.0
        top_p: 0.95
    harness:
        tasks:
            - hellaswag
            - piqa
            - task: nq_open
              num_fewshot: 5
    validation:
        max_steps: 100 
