# Template config, need to change dump_dir, data.root_dir and data.tokenizer.path

# dump_dir: !!CHANGETHIS!!

dump_dir: /data/users/yangzho6/lingua/checkpoints/webonly 

name: "webonly"
steps: 1000 
probe_freq: 10000 
grad_acc_steps: 8 
seed: 777
optim:
    lr: 3e-5 
    warmup: 1000 
    lr_min_ratio: 0.1 
    clip: 1.0 

distributed:
    fsdp_type: full_shard
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    tp_size: 1

model:
    dim: 8192 
    n_layers: 8
    n_heads: 8

data:
    root_dir: data/shuffled
    sources:
        megamath_pro_web: 100.0 
    batch_size: 1 
    prefetch_size: 64
    seq_len: 8192 
    n_views: 2
    load_async: true
    tokenizer:
        name: tiktoken 
        path: /data/users/yangzho6/lingua/checkpoints/Llama3.23B/tokenizer.model 

profiling:
    run: true

checkpoint:
    init_ckpt_path: /data/users/yangzho6/lingua/checkpoints/llama-3.2-3b-dcp 
    dump:
        every: 1000 
        keep: 5 

logging:
    freq: 10 
    wandb: 
        project: "midtrainingsyncthmath" 
        entity: "Stevenzhou0816100" 
        name: "webonly" 
